# Generated by Django 5.0.3 on 2026-01-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
