# Generated by Django 5.0.3 on 2026-02-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_medicalreport_analysisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='analysis_duration',
            field=models.FloatField(default=0.0, help_text='Analysis time in seconds'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='follow_up_actions',
            field=models.TextField(blank=True, help_text='Recommended follow-up actions', null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='recommendations',
            field=models.TextField(blank=True, help_text='AI-generated clinical recommendations', null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='cholesterol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='clinical_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='family_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='glucose',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='medications',
            field=models.TextField(blank=True, help_text='Current medications', null=True),
        ),
    ]
