# Generated by Django 5.0.3 on 2026-03-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_analysisresult_analysis_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='follow_up_actions',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='predictions_json',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='recommendations',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='alert_disease_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='alert_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='alert_risk_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='email_alert_sent',
            field=models.BooleanField(default=False),
        ),
    ]
