# Generated by Django 5.0.3 on 2026-03-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_analysisresult_follow_up_actions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='follow_up_actions',
            field=models.TextField(blank=True, help_text='Recommended follow-up actions', null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='predictions_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='recommendations',
            field=models.TextField(blank=True, help_text='AI-generated clinical recommendations', null=True),
        ),
    ]
